config/routes.rb
Rails.application.routes.draw do

  root   'pages#home'
  get    '/summary',          to: 'pages#summary'
  get    '/login',            to: 'sessions#new'
  post   '/login',            to: 'sessions#create'
  get    '/signup',           to: 'users#new'
  post   '/signup',           to: 'users#create'
  delete '/logout',           to: 'sessions#destroy'

  resources :users
  resources :group_stats,     only: [:index]
  resources :hero_stats,      only: [:index]
  resources :map_stats,       only: [:index]
  resources :map_hero_stats,  only: [:index]
  resources :time_stats,      only: [:index]
  resources :matches,         only: [:index, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group_stat.rb
class GroupStat < ApplicationRecord
  belongs_to :user
end

app/models/hero.rb
class Hero < ApplicationRecord
  belongs_to :match
  validates :hero, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 24 }
end

app/models/hero_stat.rb
class HeroStat < ApplicationRecord
  belongs_to :user
end

app/models/map_hero_stat.rb
class MapHeroStat < ApplicationRecord
  belongs_to :user
end

app/models/map_stat.rb
class MapStat < ApplicationRecord
  belongs_to :user
end

app/models/match.rb
class Match < ApplicationRecord

  belongs_to :user
  has_many :heros, dependent: :destroy
  accepts_nested_attributes_for :heros

  before_save :set_rank_change
  before_save :set_streaks

  NUM_MAPS = 14
  MAX_RANK = 5000

  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :map, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: NUM_MAPS }
  validates :rank, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: MAX_RANK }
  validates :notes, length: { maximum: 150 }
  validates :video_link, length: { maximum: 150 }

  def prev_match
    @prev_match ||= Match.find_by(user_id: user_id)
  end

  def calculate_rank_change
    return 0 if prev_match.nil?
    return rank - prev_match.rank
  end

  #fix draw assigned to first match
  def set_wld
    self.wld = 1 if calculate_rank_change > 0
    self.wld = 2 if calculate_rank_change < 0
    self.wld = 3 if calculate_rank_change == 0
  end

  def set_rank_change
    self.rank_change = calculate_rank_change
  end

  def set_streaks
    set_wld
    if prev_match.nil?
      if self.wld == 1
        self.winstreak = 1
        self.losestreak = 0
      elsif self.wld == 2
        self.winstreak = 0
        self.losestreak = 1
      elsif self.wld == 3
        self.winstreak = 0
        self.losestreak = 0
      end
      return
    end

    if (prev_match.wld == 1 && self.wld == 1) || (prev_match.wld == 2 && self.wld == 1) || (prev_match.wld == 3 && self.wld == 1)
      self.winstreak = prev_match.winstreak + 1
      self.losestreak = 0
    elsif (prev_match.wld == 2 && self.wld == 2) || (prev_match.wld == 1 && self.wld == 2) || (prev_match.wld == 3 && self.wld == 2)
      self.winstreak = 0
      self.losestreak = prev_match.losestreak + 1
    elsif self.wld == 3
      self.winstreak = prev_match.winstreak
      self.losestreak = prev_match.losestreak
    end
  end

  def self.to_csv
    columns = %w{id rank wld win_streak lose_streak map_name group_size video notes hero1, hero2, hero3, hero4}
    CSV.generate(headers: true) do |csv|
      csv << columns

      # add rank changed too
      all.each do |match|
        num_heros = match.heros.count
        csv_temp = [match.id, match.rank, ApplicationController.helpers.get_wld(match.wld), match.winstreak,
                match.losestreak, ApplicationController.helpers.get_map_name(match.map), match.group_size,
                match.video_link, match.notes]
        num_heros.times do |i|
          csv_temp << ApplicationController.helpers.get_hero_name(match.heros[i].hero)
        end
        csv << csv_temp
      end
    end
  end
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :user
end

app/models/summary.rb
class Summary < ApplicationRecord
end

app/models/time_stat.rb
class TimeStat < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :matches,         dependent: :destroy
  has_many :group_stats,     dependent: :destroy
  has_many :hero_stats,      dependent: :destroy
  has_many :map_stats,       dependent: :destroy
  has_many :map_hero_stats,  dependent: :destroy
  has_many :time_stats,      dependent: :destroy
  has_one :summaries,        dependent: :destroy
  before_save { email.downcase! }

  EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  #Cannot start with a number
  #3-12 word characters
  #followed by #
  #folowed by 2-10 digits
  BATTLETAG_REGEX = /\A\D\w{2,11}#\d{2,10}\z/

  validates :battletag, presence: true, length: { maximum: 25 },
                        format: { with: BATTLETAG_REGEX },
                        uniqueness: true
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_secure_password
end

app/helpers/constants_helper.rb
module ConstantsHelper
  def get_map_name(map_id)
    case map_id
    when 1
      'Dorado'
    when 2
      'Eichenwalde'
    when 3
      'Hanamura'
    when 4
      'Hollywood'
    when 5
      'Ilios'
    when 6
      "King's Row"
    when 7
      'Lijang Tower'
    when 8
      'Nepal'
    when 9
      'Numbani'
    when 10
      'Oasis'
    when 11
      'Route 66'
    when 12
      'Temple of Anubis'
    when 13
      'Volskaya Industries'
    when 14
      'Watchpoint: Gibraltar'
    end
  end

  def get_hero_name(hero_id)
    case hero_id
    when 1
      'Ana'
    when 2
      'Bastion'
    when 3
      'D.Va'
    when 4
      'Genji'
    when 5
      'Hanzo'
    when 6
      'Junkrat'
    when 7
      'Lucio'
    when 8
      'Mcree'
    when 9
      'Mei'
    when 10
      'Mercy'
    when 11
      'Pharah'
    when 12
      'Reaper'
    when 13
      'Reinhardt'
    when 14
      'Roadhog'
    when 15
      'Soldier: 76'
    when 16
      'Sombra'
    when 17
      'Symmetra'
    when 18
      'Torbjorn'
    when 19
      'Tracer'
    when 20
      'Widowmaker'
    when 21
      'Winston'
    when 22
      'Zarya'
    when 23
      'Zenyatta'
    end
  end

  def get_wld(wld_val)
    case wld_val
    when 1
      'Win'
    when 2
      'Lose'
    when 3
      'Draw'
    end
  end

  def get_time_id(time)
    case
    when time >= 6 && time < 9
      return 1
    when time >= 9 && time < 12
      return 2
    when time >= 12 && time < 15
      return 3
    when time >= 15 && time < 18
      return 4
    when time >= 18 && time < 21
      return 5
    when time >= 21
      return 6
    when time >= 0 && time < 3
      return 7
    when time >= 3 && time < 6
      return 8
    end
  end

  def get_time_period(time)
    case time
    when 1
      '6 - 9'
    when 2
      '9 - 12'
    when 3
      '12 - 15'
    when 4
      '15 - 18'
    when 5
      '18 - 21'
    when 6
      '21 - 0'
    when 7
      '0 - 3'
    when 8
      '3 - 6'
    end
  end

end

app/helpers/hero_stats_helper.rb
module HeroStatsHelper
  def get_chart_data_hero(hero_stats)
    chart_data = Array.new(23, 0)
    stats = hero_stats.pluck(:hero, :total_games)
    stats.each do |stat|
      chart_data[stat[0] - 1] = stat[1]
    end
    return chart_data
  end
end

app/helpers/map_stats_helper.rb
module MapStatsHelper
   def get_chart_data_map(map_stats)
    chart_data = Array.new(14, 0)
    stats = map_stats.pluck(:map, :total_games)
    stats.each do |stat|
      chart_data[stat[0] - 1] = stat[1]
    end
    return chart_data
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def cur_user
    @cur_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !cur_user.nil?
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @cur_user = nil
  end
end

app/helpers/stats_helper.rb
module StatsHelper
  def is_win(wld)
    return 1 if wld == 1
    return 0
  end

  def is_lose(wld)
    return 1 if wld == 2
    return 0
  end

  def is_draw(wld)
    return 1 if wld == 3
    return 0
  end

  def win_ratio(wins, total_games)
    ((wins/total_games.to_f) * 100).round(2)
  end
end

app/helpers/time_stats_helper.rb
module TimeStatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_defaultrails.html.haml
= csrf_meta_tags
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/_footer.haml.erb
%footer.footer
  %small
    The
    %a{:href => "http://www.railstutorial.org/"} Ruby on Rails Tutorial
    by
    %a{:href => "http://www.michaelhartl.com/"} Michael Hartl
  %nav
    %ul
      %li= link_to "About",   '#'
      %li= link_to "Contact", '#'
      %li
        %a{:href => "http://news.railstutorial.org/"} News

app/views/layouts/_footer.html.haml
%footer.footer
  %div.container
    %div.col-xs-4.col-xs-offset-4
      %small
        %a{:href => root_path}  OVERTRACKER 
        %p: &nbsp; Let the Stats Flow

    /%div.row
    /  %div.col-xs-12
    /    %nav
    /      %ul
    /        %li= link_to "About",   '#'
    /        %li= link_to "Contact", '#'
    /        %li= link_to "Stats", '#'
    /        %li
    /          %a{:href => "#"} News

app/views/layouts/_header.haml.erb
%header.navbar.navbar-fixed-top.navbar-inverse
  %div.container
    = link_to "sample app", '#', id: "logo"
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Home",   '#'
        %li= link_to "Help",   '#'
        %li= link_to "Log in", '#'

app/views/layouts/_header.html.haml
%header.transparent.navbar
  %div.container
    %div#logo-holder
      %a#logo{:href => root_url}
        %img{:src => image_url("logo.png"), title:"OverTracker", alt:"OverTracker"}
    %nav.cs-nav
      %div.navbar-header
        %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
      %div#bs-example-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          - if logged_in?
            %li= link_to "Add Match", new_match_path
            %li= link_to "Matches", matches_path
            %li= link_to "Hero", hero_stats_path
            %li= link_to "Map", map_stats_path
            %li= link_to "Per Map", map_hero_stats_path
            %li= link_to "Group", group_stats_path
            %li= link_to "Time", time_stats_path
            %li= link_to "Settings", edit_user_path(cur_user)
            %li{:class => 'csbuttons'}
              = link_to "Logout", logout_path, method: "delete"
          - else
            %li= link_to "Signup", signup_path
            %li{:class => 'csbuttons'}
              = link_to "Login", login_path

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_user_data_edit.html.haml
%div.row
  %div.col-sm-6.col-sm-offset-3
    = form_for(@user) do |f|
      = render 'shared/error_messages'
      = f.label :battletag, class: "field-labels", value: "Battle Tag:"
      = f.text_field :battletag, class: "input-fields form-control", placeholder: "Enter Battle Tag\..."
      = f.label :email, class: "field-labels", value: "Email:"
      = f.email_field :email, class: "input-fields form-control", placeholder: "Email Address\..."
      = f.label :password, class: "field-labels", value: "password:"
      = f.password_field :password, class: "input-fields form-control", placeholder: "Password\..."
      = f.label :password_confirmation, value: "Password Confirmation:", class: "field-labels"
      = f.password_field :password_confirmation, class: "input-fields form-control", placeholder: "Confirm Password\..."
      = f.submit yield(:var3), class: "csbuttons c-btn c-btn--primary"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/

    %title OverTrack
    = render 'layouts/defaultrails'
    = render 'layouts/shim.html.erb'
  %body
    = render 'layouts/header'
    %div.page-main-content
      %div.container-fuild
        %div.dark-theme
          %div.container
            %div#flash.col-xs-6.col-xs-offset-3
              - flash.each do |message_type, message|
                .alert{:class => "alert-" + message_type }= message
          = yield

        /= debug(params) if Rails.env.development?
    = render 'layouts/footer'

    :javascript
      $(function(){
        $('#keywords').tablesorter();
      });


    :javascript
      $(document).ready(function(){
        setTimeout(function(){
          $('#flash').remove();
            }, 10000);
              })

app/views/pages/_summary.html.haml
%table#keywords.matchesdatatable
  %thead.tbl-header
    %tr
      %th
        %span
          Total Games
      %th
        %span
          Lowest SR
      %th
        %span
          Highest SR
      %th
        %span
          Wins
      %th
        %span
          Loses
      %th
        %span
          Draws
      %th
        %span
          Longest Win Streak
      %th
        %span
          Longest Lose Streak
  %tbody.tbl-content
    %tr
      %td
        = @total_games
      %td
        = @lowest_sr
      %td
        = @highest_sr
      %td
        = @wins
      %td
        = @losses
      %td
        = @draws
      %td
        = @longest_win_streak
      %td
        = @longest_lose_streak

app/views/pages/home.haml.erb
%h1 Pages#home
%p Find me in app/views/pages/home.html.erb

app/views/pages/home.html.haml
%div.container-fuild
  %main.hometopsec
    %div.intro-message
      %h1.main-heading
        OverTracker Personal Game Stats Tracker
      %h3.main-heading-desc
        You gonna perform better if you know where to push

      - unless logged_in?
        %div.container
          %div.col-sm-6.col-sm-offset-3
            %div.col-sm-6
              %button.csbuttons.c-btn.c-btn--primary.c-btn-home #{link_to "Login", login_path}
            %div.col-sm-6
              %button.csbuttons.c-btn.c-btn--primary.c-btn-home #{link_to "Sign up", signup_path}
      - if logged_in?
        %div.container
          %div.col-sm-10.col-sm-offset-1
            = render 'pages/summary'
%div.container-fuild.light-theme.home-page
  %div.container
    %section.col-xs-12.col-sm-5.left.main-page-img
      %img{:src => image_url("imac-final.png")}
    %section.col-xs-12.col-sm-6.right.main-page-section
      %h1.titletag
        Record results of your matches
      %h3.titledesc
        Create a new record with match results after each match to gather detailed
        statistics on your playing skills
  %div.container-fuild.dark-theme
    %div.container
      %section.col-xs-12.col-sm-5.right.main-page-img
        %img{:src => image_url("ipad-final.png")}
      %section.col-xs-12.col-sm-6.left.main-page-section
        %h1.titletag
          Observe various statistics
        %h3.titledesc
          Know your strengths and weaknesses: Look on your performance as each
          hero on each map and get crystal clear picture on what you should work harder
  %div.container
    %section.col-xs-12.col-sm-5.left.main-page-img
      %img{:src => image_url("iphone-final.png")}
    %section.col-xs-12.col-sm-6.right.main-page-section
      %h1.titletag
        Grow your Skill Rating
      %h3.titledesc
        Train harder on heroes and maps you want to perform better.
        Statistics is a perfect tool to see where you should push harder
  - unless logged_in?
    %div.container-fuild
      %section.col-sm-12.awesome-container
        %h2.awesome
          Login to discover how awesome we are
  %div.container-fuild
    %section.col-sm-12.bg-mountain-city.show-for-lg
      %div.container
        %section.col-sm-12.main-page-section
          %h1.main-heading
            Built for the Gamers by the Gamers!
          %h3.main-heading-desc
            No matter your playstyle, there’s a unique hero for you.<br/>
            Master their abilities to unlock their <br/>potential and achieve victory.

  %div.container-fuild.bg-musem
    %div.container
      %section.col-xs-12.col-sm-5.tracer-img.left
        %img{:src => "http://vignette3.wikia.nocookie.net/deathbattlefanon/images/9/99/Tracer.png/revision/latest?cb=20160529142716"}/
      %section.col-xs-12.col-sm-5.right.main-page-section.right
        %h1.titletag
          Watch Your Stats
        %h3.titledesc
          Statistics is your way to win. The world could use a hero like you.
        - unless logged_in?
          %col-sm-12
            %div.col-sm-12
              %button.csbuttons.c-btn.c-btn--primary Sign up#{link_to "", signup_path}

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  %div#error_explanation
    %div.alert.alert-danger
      There are
      = pluralize(@user.errors.count, "error")
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg